apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/wbrefvem/bdd-rails-shopping-cart-1551388121:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/wbrefvem/bdd-rails-shopping-cart-1551388121:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: bdd-rails-shopping-cart-1551388121
        chartPath: charts/bdd-rails-shopping-cart-1551388121
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/wbrefvem/bdd-rails-shopping-cart-1551388121'
          image.tag: '{{.DIGEST_HEX}}'
